export const T4A_FIELD_MAPPINGS = {
  recipientType: ["Recipient Type", "Type of Recipient"],
  recipientName: {
    snm: ["Surname", "Last Name", "Family Name"],
    gvn_nm: ["Given Name", "First Name"],
    init: ["Middle Initial"],
  },
  recipientCorpName: {
    l1_nm: ["Corporate Name Line 1", "Business Name Line 1"],
    l2_nm: ["Corporate Name Line 2", "Business Name Line 2"],
  },
  sin: ["Social Insurance Number", "SIN"],
  rcpnt_bn: ["Recipient Business Number", "Recipient BN"],
  recipientAddress: {
    addr_l1_txt: ["Address Line 1", "Street Address"],
    addr_l2_txt: ["Address Line 2", "Apartment, Suite, Unit"],
    cty_nm: ["City", "Town"],
    prov_cd: ["Province", "State"],
    cntry_cd: ["Country", "Nation"],
    pstl_cd: ["Postal Code", "ZIP Code"],
  },
  rcpnt_nbr: ["Recipient Number"],
  bn: ["Business Number", "BN"],
  payr_dntl_ben_rpt_cd: ["Payer Dental Benefit Report Code"],
  ppln_dpsp_rgst_nbr: ["Pension Plan or DPSP Registration Number"],
  rpt_tcd: ["Report Type Code"],
  amounts: {
    pens_spran_amt: ["Pension or Superannuation Amount"],
    lsp_amt: ["Lump-sum Payment Amount"],
    self_empl_cmsn_amt: ["Self-employment Commission Amount"],
    itx_ddct_amt: ["Income Tax Deducted Amount"],
    annty_amt: ["Annuity Amount"],
    fee_or_oth_srvc_amt: ["Amount", "Fee or Other Service Amount"],
  },
  otherInfo: {
    elg_rtir_amt: ["Eligible Retiring Allowances"],
    nelg_rtir_amt: ["Non-eligible Retiring Allowances"],
    oth_incamt: ["Other Income"],
    ptrng_aloc_amt: ["Patronage Allocations"],
    rpp_past_srvc_amt: ["Registered Pension Plan Contributions - Past Service"],
    padj_amt: ["Pension Adjustment"],
    alda_amt: ["Advanced Life Deferred Annuity Purchase"],
    resp_aip_amt: ["RESP Accumulated Income Payments"],
    resp_educt_ast_amt: ["RESP Educational Assistance Payments"],
    chrty_dons_amt: ["Charitable Donations"],
    nr_lsp_trnsf_amt: ["Lump-sum Payments - Non-resident Services Transfer"],
    rsch_grnt_amt: ["Research Grants"],
    brsy_amt: ["Scholarships, Fellowships, or Bursaries"],
    dth_ben_amt: ["Death Benefits"],
    wag_ls_incamt: ["Wage Loss Replacement Plan Income"],
    lsp_rpp_nelg_amt: ["RPP Lump-sum Payments - Not Eligible for Transfer"],
    nrgst_ppln_amt: ["Unregistered Pension Plan"],
    pr_71_acr_lsp_amt: ["Lump-sum Payments Accrued to December 31, 1971"],
    inc_avg_annty_amt: ["IAAC Annuities"],
    dpsp_ins_pay_amt: ["DPSP Installment or Annuity Payments"],
    med_trvl_amt: ["Medical Travel"],
    loan_ben_amt: ["Loan Benefit under Subsection 80.4(2)"],
    med_prem_ben_amt: ["Medical Premium Benefit"],
    grp_trm_life_amt: ["Group Term Life Insurance Benefit"],
    resp_aip_oth_amt: ["RESP Accumulated Income Payments to Other"],
    ins_rvk_dpsp_amt: ["Revoked DPSP Installment or Annuity Payments"],
    brd_wrk_site_amt: ["Board and Lodging at Special Work Sites"],
    dsblt_ben_amt: ["Disability Benefits"],
    cntrbr_prr_pspp_cnamt: ["Contributor RPP Past Service Pre-1990 Contributions"],
    vtrn_ben_amt: ["Veteran's Benefit"],
    vtrn_ben_pens_splt_elg_amt: ["Veterans' Benefits Eligible for Pension Splitting"],
    tx_dfr_ptrng_dvamt: ["Tax Deferred Patronage Dividends"],
    atp_inctv_grnt_amt: ["Apprenticeship Incentive/Completion Grant"],
    rdsp_amt: ["Registered Disability Savings Plan"],
    wag_ptct_pgm_amt: ["Wage Earner Protection Program"],
    var_pens_ben_amt: ["Variable Pension Benefits"],
    tfsa_tax_amt: ["TFSA/FHSA Taxable Amount"],
    rcpnt_pay_prem_phsp_amt: ["Recipient-paid Private Health Services Plan Premiums"],
    pmmc_isg_amt: ["Parents of Murdered/Missing Children Benefits"],
    indn_oth_incamt: ["Indian Act - Exempt Other Income"],
    indn_xmpt_pens_amt: ["Indian Act - Exempt Pension/Superannuation"],
    indn_xmpt_lsp_amt: ["Indian Act - Exempt Lump-sum Payments"],
    lbr_adj_ben_aprpt_act_amt: ["Labour Adjustment Benefits"],
    subp_qlf_amt: ["SUBP Qualified Under Income Tax Act"],
    csh_awrd_pze_payr_amt: ["Cash Award or Prize from Payer"],
    bkcy_sttl_amt: ["Bankruptcy Settlement"],
    lsp_nelg_trnsf_amt: ["Lump-sum Payments - Not Eligible for Transfer"],
    ncntrbr_prr_pspp_cnamt: ["Non-Contributor RPP Past Service Pre-1990"],
    lsp_dpsp_nelg_amt: ["DPSP Lump-sum Payments - Not Eligible for Transfer"],
    lsp_nrgst_pens_amt: ["Unregistered Pension Benefits Lump-sum"],
    prpp_tx_inc_pamt: ["PRPP Payments"],
    prpp_txmpt_inc_pamt: ["Indian Act - Exempt PRPP Payments"],
    abe_tuit_ast_amt: ["Adult Basic Education Tuition Assistance"],
    prov_trty_emrg_ben_amt: ["Provincial/Territorial COVID-19 Assistance"],
    repmt_covid_fncl_asstnc: ["Repayment of COVID-19 Financial Assistance"],
    oas_lump_sum_pamt: ["One-time Payment for Older Seniors"],
    pst_dctrl_fshp_amt: ["Postdoctoral Fellowship Income"],
  },
  addInfo: {
    spp_sps_cntrb_ind: ["Spousal Contributions Indicator"],
    spp_sps_cntrbr_sin: ["Spousal Contributor SIN"],
  },
};

export const T4A_DYNAMIC_FIELD_MAPPINGS = {
  recipientName: ["Name"],
  recipientAddress: ["Address"],
};
